FROM confluence

USER root:root

ENV OS_USERNAME confluence
ENV OS_GROUPNAME confluence
ENV CONFLUENCE_HOME /var/atlassian/application-data/confluence
ENV CONFLUENCE_INSTALL=/opt/atlassian/confluence

COPY okta_acs.jsp ${CONFLUENCE_INSTALL}/confluence

RUN curl https://stratavo-admin.okta.com/static/toolkits/okta-confluence-3.1.5.jar -o ${CONFLUENCE_INSTALL}/confluence/WEB-INF/lib/okta-confluence-3.1.5.jar \
  && chown -R ${OS_USERNAME}:${OS_GROUPNAME} ${CONFLUENCE_INSTALL} \
  && ln -s ${CONFLUENCE_INSTALL}/confluence/WEB-INF/classes/seraph-config.xml ${CONFLUENCE_HOME}/seraph-config.xml \
  && sync 

USER ${OS_USERNAME}:${OS_GROUPNAME}
